# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArduinoPythonTest.ui',
# licensing of 'ArduinoPythonTest.ui' applies.
#
# Created: Tue May  5 12:14:54 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CommQTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.CommQTextBrowser.setObjectName("CommQTextBrowser")
        self.gridLayout.addWidget(self.CommQTextBrowser, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.COM_Label = QtWidgets.QLabel(self.centralwidget)
        self.COM_Label.setObjectName("COM_Label")
        self.horizontalLayout_2.addWidget(self.COM_Label)
        self.COM_Input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COM_Input.sizePolicy().hasHeightForWidth())
        self.COM_Input.setSizePolicy(sizePolicy)
        self.COM_Input.setObjectName("COM_Input")
        self.horizontalLayout_2.addWidget(self.COM_Input)
        self.ConnectedRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ConnectedRadioButton.setObjectName("ConnectedRadioButton")
        self.horizontalLayout_2.addWidget(self.ConnectedRadioButton)
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout_2.addWidget(self.ConnectButton)
        self.DisconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.horizontalLayout_2.addWidget(self.DisconnectButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ModeSelect_Label = QtWidgets.QLabel(self.centralwidget)
        self.ModeSelect_Label.setCursor(QtCore.Qt.ArrowCursor)
        self.ModeSelect_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ModeSelect_Label.setObjectName("ModeSelect_Label")
        self.horizontalLayout_3.addWidget(self.ModeSelect_Label)
        self.ModeSelectDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.ModeSelectDropDown.setObjectName("ModeSelectDropDown")
        self.ModeSelectDropDown.addItem("")
        self.ModeSelectDropDown.addItem("")
        self.ModeSelectDropDown.addItem("")
        self.ModeSelectDropDown.addItem("")
        self.horizontalLayout_3.addWidget(self.ModeSelectDropDown)
        self.UploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.UploadButton.setObjectName("UploadButton")
        self.horizontalLayout_3.addWidget(self.UploadButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.VariableTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VariableTabWidget.sizePolicy().hasHeightForWidth())
        self.VariableTabWidget.setSizePolicy(sizePolicy)
        self.VariableTabWidget.setObjectName("VariableTabWidget")
        self.GeneralTab = QtWidgets.QWidget()
        self.GeneralTab.setObjectName("GeneralTab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.GeneralTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 451, 251))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.GeneralQGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.GeneralQGrid.setContentsMargins(0, 0, 0, 0)
        self.GeneralQGrid.setObjectName("GeneralQGrid")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.GeneralQGrid.addItem(spacerItem3, 3, 0, 1, 1)
        self.NewValQLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.NewValQLabel_3.setMinimumSize(QtCore.QSize(98, 0))
        self.NewValQLabel_3.setMaximumSize(QtCore.QSize(98, 16777215))
        self.NewValQLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.NewValQLabel_3.setObjectName("NewValQLabel_3")
        self.GeneralQGrid.addWidget(self.NewValQLabel_3, 0, 2, 1, 1)
        self.NumStepsQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.NumStepsQLineEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.NumStepsQLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.NumStepsQLineEdit.setObjectName("NumStepsQLineEdit")
        self.GeneralQGrid.addWidget(self.NumStepsQLineEdit, 1, 2, 1, 1)
        self.RunsPerStepQLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.RunsPerStepQLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.RunsPerStepQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RunsPerStepQLabel.setObjectName("RunsPerStepQLabel")
        self.GeneralQGrid.addWidget(self.RunsPerStepQLabel, 2, 0, 1, 1)
        self.RunsPerStepQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.RunsPerStepQLineEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.RunsPerStepQLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.RunsPerStepQLineEdit.setObjectName("RunsPerStepQLineEdit")
        self.GeneralQGrid.addWidget(self.RunsPerStepQLineEdit, 2, 2, 1, 1)
        self.NumStepsQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_5)
        self.NumStepsQLCD.setMaximumSize(QtCore.QSize(122, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.NumStepsQLCD.setFont(font)
        self.NumStepsQLCD.setSmallDecimalPoint(False)
        self.NumStepsQLCD.setDigitCount(10)
        self.NumStepsQLCD.setMode(QtWidgets.QLCDNumber.Dec)
        self.NumStepsQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.NumStepsQLCD.setObjectName("NumStepsQLCD")
        self.GeneralQGrid.addWidget(self.NumStepsQLCD, 1, 1, 1, 1)
        self.RunsPerStepQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_5)
        self.RunsPerStepQLCD.setMaximumSize(QtCore.QSize(122, 16777215))
        self.RunsPerStepQLCD.setDigitCount(10)
        self.RunsPerStepQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.RunsPerStepQLCD.setObjectName("RunsPerStepQLCD")
        self.GeneralQGrid.addWidget(self.RunsPerStepQLCD, 2, 1, 1, 1)
        self.CurrentValQLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.CurrentValQLabel_3.setMinimumSize(QtCore.QSize(122, 0))
        self.CurrentValQLabel_3.setMaximumSize(QtCore.QSize(122, 16777215))
        self.CurrentValQLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentValQLabel_3.setObjectName("CurrentValQLabel_3")
        self.GeneralQGrid.addWidget(self.CurrentValQLabel_3, 0, 1, 1, 1)
        self.NumStepsQLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.NumStepsQLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.NumStepsQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NumStepsQLabel.setObjectName("NumStepsQLabel")
        self.GeneralQGrid.addWidget(self.NumStepsQLabel, 1, 0, 1, 1)
        self.VariableQLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.VariableQLabel_3.setMinimumSize(QtCore.QSize(155, 0))
        self.VariableQLabel_3.setMaximumSize(QtCore.QSize(122, 16777215))
        self.VariableQLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.VariableQLabel_3.setObjectName("VariableQLabel_3")
        self.GeneralQGrid.addWidget(self.VariableQLabel_3, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.GeneralQGrid.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.GeneralQGrid.addWidget(self.label_11, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.GeneralQGrid.addWidget(self.label_12, 1, 3, 1, 1)
        self.VariableTabWidget.addTab(self.GeneralTab, "")
        self.FreqSweepTab = QtWidgets.QWidget()
        self.FreqSweepTab.setObjectName("FreqSweepTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.FreqSweepTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 252))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.FreqSweepGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.FreqSweepGrid.setContentsMargins(0, 0, 0, 0)
        self.FreqSweepGrid.setObjectName("FreqSweepGrid")
        self.SweepCenterFreqQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepCenterFreqQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepCenterFreqQLineEdit.setObjectName("SweepCenterFreqQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepCenterFreqQLineEdit, 3, 2, 1, 1)
        self.SweepRateQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepRateQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepRateQLCD.setDigitCount(10)
        self.SweepRateQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepRateQLCD.setObjectName("SweepRateQLCD")
        self.FreqSweepGrid.addWidget(self.SweepRateQLCD, 4, 1, 1, 1)
        self.SweepRateStopQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepRateStopQLabel.sizePolicy().hasHeightForWidth())
        self.SweepRateStopQLabel.setSizePolicy(sizePolicy)
        self.SweepRateStopQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepRateStopQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepRateStopQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepRateStopQLabel.setObjectName("SweepRateStopQLabel")
        self.FreqSweepGrid.addWidget(self.SweepRateStopQLabel, 7, 0, 1, 1)
        self.SweepRateStopQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepRateStopQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepRateStopQLineEdit.setObjectName("SweepRateStopQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepRateStopQLineEdit, 7, 2, 1, 1)
        self.NewValQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.NewValQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NewValQLabel.setObjectName("NewValQLabel")
        self.FreqSweepGrid.addWidget(self.NewValQLabel, 0, 2, 1, 1)
        self.SweepSpanQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepSpanQLabel.sizePolicy().hasHeightForWidth())
        self.SweepSpanQLabel.setSizePolicy(sizePolicy)
        self.SweepSpanQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepSpanQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepSpanQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepSpanQLabel.setObjectName("SweepSpanQLabel")
        self.FreqSweepGrid.addWidget(self.SweepSpanQLabel, 5, 0, 1, 1)
        self.SweepCenterFreqQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepCenterFreqQLabel.sizePolicy().hasHeightForWidth())
        self.SweepCenterFreqQLabel.setSizePolicy(sizePolicy)
        self.SweepCenterFreqQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepCenterFreqQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepCenterFreqQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepCenterFreqQLabel.setObjectName("SweepCenterFreqQLabel")
        self.FreqSweepGrid.addWidget(self.SweepCenterFreqQLabel, 3, 0, 1, 1)
        self.SweepSpanQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepSpanQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepSpanQLineEdit.setObjectName("SweepSpanQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepSpanQLineEdit, 5, 2, 1, 1)
        self.SweepUpperBoundQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepUpperBoundQLCD.setMaximumSize(QtCore.QSize(122, 50))
        self.SweepUpperBoundQLCD.setDigitCount(10)
        self.SweepUpperBoundQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepUpperBoundQLCD.setObjectName("SweepUpperBoundQLCD")
        self.FreqSweepGrid.addWidget(self.SweepUpperBoundQLCD, 1, 1, 1, 1)
        self.SweepUpperBoundQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepUpperBoundQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepUpperBoundQLineEdit.setObjectName("SweepUpperBoundQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepUpperBoundQLineEdit, 1, 2, 1, 1)
        self.SweepRateQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepRateQLabel.sizePolicy().hasHeightForWidth())
        self.SweepRateQLabel.setSizePolicy(sizePolicy)
        self.SweepRateQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepRateQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepRateQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepRateQLabel.setObjectName("SweepRateQLabel")
        self.FreqSweepGrid.addWidget(self.SweepRateQLabel, 4, 0, 1, 1)
        self.SweepCenterFreqQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepCenterFreqQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepCenterFreqQLCD.setDigitCount(10)
        self.SweepCenterFreqQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepCenterFreqQLCD.setObjectName("SweepCenterFreqQLCD")
        self.FreqSweepGrid.addWidget(self.SweepCenterFreqQLCD, 3, 1, 1, 1)
        self.VariableQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VariableQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VariableQLabel.setObjectName("VariableQLabel")
        self.FreqSweepGrid.addWidget(self.VariableQLabel, 0, 0, 1, 1)
        self.SweepLowerBoundQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepLowerBoundQLabel.sizePolicy().hasHeightForWidth())
        self.SweepLowerBoundQLabel.setSizePolicy(sizePolicy)
        self.SweepLowerBoundQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepLowerBoundQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepLowerBoundQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepLowerBoundQLabel.setObjectName("SweepLowerBoundQLabel")
        self.FreqSweepGrid.addWidget(self.SweepLowerBoundQLabel, 2, 0, 1, 1)
        self.SweepLowerBoundQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepLowerBoundQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepLowerBoundQLineEdit.setObjectName("SweepLowerBoundQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepLowerBoundQLineEdit, 2, 2, 1, 1)
        self.SweepRateStartQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepRateStartQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepRateStartQLineEdit.setObjectName("SweepRateStartQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepRateStartQLineEdit, 6, 2, 1, 1)
        self.SweepLowerBoundQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepLowerBoundQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepLowerBoundQLCD.setDigitCount(10)
        self.SweepLowerBoundQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepLowerBoundQLCD.setObjectName("SweepLowerBoundQLCD")
        self.FreqSweepGrid.addWidget(self.SweepLowerBoundQLCD, 2, 1, 1, 1)
        self.SweepUpperBoundQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepUpperBoundQLabel.sizePolicy().hasHeightForWidth())
        self.SweepUpperBoundQLabel.setSizePolicy(sizePolicy)
        self.SweepUpperBoundQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepUpperBoundQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepUpperBoundQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepUpperBoundQLabel.setObjectName("SweepUpperBoundQLabel")
        self.FreqSweepGrid.addWidget(self.SweepUpperBoundQLabel, 1, 0, 1, 1)
        self.SweepRateQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SweepRateQLineEdit.setMaximumSize(QtCore.QSize(98, 50))
        self.SweepRateQLineEdit.setObjectName("SweepRateQLineEdit")
        self.FreqSweepGrid.addWidget(self.SweepRateQLineEdit, 4, 2, 1, 1)
        self.SweepRateStartQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepRateStartQLabel.sizePolicy().hasHeightForWidth())
        self.SweepRateStartQLabel.setSizePolicy(sizePolicy)
        self.SweepRateStartQLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SweepRateStartQLabel.setBaseSize(QtCore.QSize(200, 50))
        self.SweepRateStartQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SweepRateStartQLabel.setObjectName("SweepRateStartQLabel")
        self.FreqSweepGrid.addWidget(self.SweepRateStartQLabel, 6, 0, 1, 1)
        self.SweepRateStartQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepRateStartQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepRateStartQLCD.setDigitCount(10)
        self.SweepRateStartQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepRateStartQLCD.setObjectName("SweepRateStartQLCD")
        self.FreqSweepGrid.addWidget(self.SweepRateStartQLCD, 6, 1, 1, 1)
        self.SweepSpanQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepSpanQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepSpanQLCD.setDigitCount(10)
        self.SweepSpanQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepSpanQLCD.setObjectName("SweepSpanQLCD")
        self.FreqSweepGrid.addWidget(self.SweepSpanQLCD, 5, 1, 1, 1)
        self.CurrentValQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.CurrentValQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentValQLabel.setObjectName("CurrentValQLabel")
        self.FreqSweepGrid.addWidget(self.CurrentValQLabel, 0, 1, 1, 1)
        self.SweepRateStopQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.SweepRateStopQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.SweepRateStopQLCD.setDigitCount(10)
        self.SweepRateStopQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SweepRateStopQLCD.setObjectName("SweepRateStopQLCD")
        self.FreqSweepGrid.addWidget(self.SweepRateStopQLCD, 7, 1, 1, 1)
        self.SweepUpperBoundUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepUpperBoundUnitComboBox.sizePolicy().hasHeightForWidth())
        self.SweepUpperBoundUnitComboBox.setSizePolicy(sizePolicy)
        self.SweepUpperBoundUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.SweepUpperBoundUnitComboBox.setObjectName("SweepUpperBoundUnitComboBox")
        self.SweepUpperBoundUnitComboBox.addItem("")
        self.SweepUpperBoundUnitComboBox.addItem("")
        self.SweepUpperBoundUnitComboBox.addItem("")
        self.FreqSweepGrid.addWidget(self.SweepUpperBoundUnitComboBox, 1, 3, 1, 1)
        self.SweepLowerBoundUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepLowerBoundUnitComboBox.sizePolicy().hasHeightForWidth())
        self.SweepLowerBoundUnitComboBox.setSizePolicy(sizePolicy)
        self.SweepLowerBoundUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.SweepLowerBoundUnitComboBox.setObjectName("SweepLowerBoundUnitComboBox")
        self.SweepLowerBoundUnitComboBox.addItem("")
        self.SweepLowerBoundUnitComboBox.addItem("")
        self.SweepLowerBoundUnitComboBox.addItem("")
        self.FreqSweepGrid.addWidget(self.SweepLowerBoundUnitComboBox, 2, 3, 1, 1)
        self.SweepCenterFreqUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepCenterFreqUnitComboBox.sizePolicy().hasHeightForWidth())
        self.SweepCenterFreqUnitComboBox.setSizePolicy(sizePolicy)
        self.SweepCenterFreqUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.SweepCenterFreqUnitComboBox.setObjectName("SweepCenterFreqUnitComboBox")
        self.SweepCenterFreqUnitComboBox.addItem("")
        self.SweepCenterFreqUnitComboBox.addItem("")
        self.SweepCenterFreqUnitComboBox.addItem("")
        self.FreqSweepGrid.addWidget(self.SweepCenterFreqUnitComboBox, 3, 3, 1, 1)
        self.SweepSpanUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepSpanUnitComboBox.sizePolicy().hasHeightForWidth())
        self.SweepSpanUnitComboBox.setSizePolicy(sizePolicy)
        self.SweepSpanUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.SweepSpanUnitComboBox.setObjectName("SweepSpanUnitComboBox")
        self.SweepSpanUnitComboBox.addItem("")
        self.SweepSpanUnitComboBox.addItem("")
        self.SweepSpanUnitComboBox.addItem("")
        self.FreqSweepGrid.addWidget(self.SweepSpanUnitComboBox, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.FreqSweepGrid.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.FreqSweepGrid.addWidget(self.label_6, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.FreqSweepGrid.addWidget(self.label_7, 6, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.FreqSweepGrid.addWidget(self.label_8, 7, 3, 1, 1)
        self.VariableTabWidget.addTab(self.FreqSweepTab, "")
        self.SFplusTab = QtWidgets.QWidget()
        self.SFplusTab.setObjectName("SFplusTab")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.SFplusTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 451, 251))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.SFplusQGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.SFplusQGrid.setContentsMargins(0, 0, 0, 0)
        self.SFplusQGrid.setObjectName("SFplusQGrid")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.SFplusQGrid.addWidget(self.label, 4, 3, 1, 1)
        self.OutputFreqUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputFreqUnitComboBox.sizePolicy().hasHeightForWidth())
        self.OutputFreqUnitComboBox.setSizePolicy(sizePolicy)
        self.OutputFreqUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.OutputFreqUnitComboBox.setObjectName("OutputFreqUnitComboBox")
        self.OutputFreqUnitComboBox.addItem("")
        self.OutputFreqUnitComboBox.addItem("")
        self.OutputFreqUnitComboBox.addItem("")
        self.SFplusQGrid.addWidget(self.OutputFreqUnitComboBox, 1, 3, 1, 1)
        self.FreqStopQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.FreqStopQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.FreqStopQLineEdit.setObjectName("FreqStopQLineEdit")
        self.SFplusQGrid.addWidget(self.FreqStopQLineEdit, 3, 2, 1, 1)
        self.FreqStartUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FreqStartUnitComboBox.sizePolicy().hasHeightForWidth())
        self.FreqStartUnitComboBox.setSizePolicy(sizePolicy)
        self.FreqStartUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.FreqStartUnitComboBox.setObjectName("FreqStartUnitComboBox")
        self.FreqStartUnitComboBox.addItem("")
        self.FreqStartUnitComboBox.addItem("")
        self.FreqStartUnitComboBox.addItem("")
        self.SFplusQGrid.addWidget(self.FreqStartUnitComboBox, 2, 3, 1, 1)
        self.FreqStartQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.FreqStartQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.FreqStartQLCD.setDigitCount(10)
        self.FreqStartQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.FreqStartQLCD.setObjectName("FreqStartQLCD")
        self.SFplusQGrid.addWidget(self.FreqStartQLCD, 2, 1, 1, 1)
        self.PulseTimeQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.PulseTimeQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeQLCD.setDigitCount(10)
        self.PulseTimeQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PulseTimeQLCD.setObjectName("PulseTimeQLCD")
        self.SFplusQGrid.addWidget(self.PulseTimeQLCD, 4, 1, 1, 1)
        self.PulseTimeStopQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.PulseTimeStopQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeStopQLCD.setDigitCount(10)
        self.PulseTimeStopQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PulseTimeStopQLCD.setObjectName("PulseTimeStopQLCD")
        self.SFplusQGrid.addWidget(self.PulseTimeStopQLCD, 6, 1, 1, 1)
        self.CurrentValQLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.CurrentValQLabel_2.setMaximumSize(QtCore.QSize(122, 16777215))
        self.CurrentValQLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentValQLabel_2.setObjectName("CurrentValQLabel_2")
        self.SFplusQGrid.addWidget(self.CurrentValQLabel_2, 0, 1, 1, 1)
        self.PulseTimeQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.PulseTimeQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.PulseTimeQLineEdit.setObjectName("PulseTimeQLineEdit")
        self.SFplusQGrid.addWidget(self.PulseTimeQLineEdit, 4, 2, 1, 1)
        self.PulseTimeQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.PulseTimeQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PulseTimeQLabel.setObjectName("PulseTimeQLabel")
        self.SFplusQGrid.addWidget(self.PulseTimeQLabel, 4, 0, 1, 1)
        self.PulseTimeStartQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.PulseTimeStartQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.PulseTimeStartQLineEdit.setObjectName("PulseTimeStartQLineEdit")
        self.SFplusQGrid.addWidget(self.PulseTimeStartQLineEdit, 5, 2, 1, 1)
        self.PulseTimeStartQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.PulseTimeStartQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeStartQLCD.setDigitCount(10)
        self.PulseTimeStartQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.PulseTimeStartQLCD.setObjectName("PulseTimeStartQLCD")
        self.SFplusQGrid.addWidget(self.PulseTimeStartQLCD, 5, 1, 1, 1)
        self.FreqStartQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.FreqStartQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.FreqStartQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FreqStartQLabel.setObjectName("FreqStartQLabel")
        self.SFplusQGrid.addWidget(self.FreqStartQLabel, 2, 0, 1, 1)
        self.PulseTimeStartQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.PulseTimeStartQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeStartQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PulseTimeStartQLabel.setObjectName("PulseTimeStartQLabel")
        self.SFplusQGrid.addWidget(self.PulseTimeStartQLabel, 5, 0, 1, 1)
        self.FreqStopQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.FreqStopQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.FreqStopQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FreqStopQLabel.setObjectName("FreqStopQLabel")
        self.SFplusQGrid.addWidget(self.FreqStopQLabel, 3, 0, 1, 1)
        self.OutputFreqQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputFreqQLabel.sizePolicy().hasHeightForWidth())
        self.OutputFreqQLabel.setSizePolicy(sizePolicy)
        self.OutputFreqQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.OutputFreqQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputFreqQLabel.setObjectName("OutputFreqQLabel")
        self.SFplusQGrid.addWidget(self.OutputFreqQLabel, 1, 0, 1, 1)
        self.OutputFreqQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.OutputFreqQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.OutputFreqQLineEdit.setObjectName("OutputFreqQLineEdit")
        self.SFplusQGrid.addWidget(self.OutputFreqQLineEdit, 1, 2, 1, 1)
        self.PulseTimeStopQLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.PulseTimeStopQLabel.setMaximumSize(QtCore.QSize(200, 50))
        self.PulseTimeStopQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PulseTimeStopQLabel.setObjectName("PulseTimeStopQLabel")
        self.SFplusQGrid.addWidget(self.PulseTimeStopQLabel, 6, 0, 1, 1)
        self.FreqStopQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.FreqStopQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.FreqStopQLCD.setDigitCount(10)
        self.FreqStopQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.FreqStopQLCD.setObjectName("FreqStopQLCD")
        self.SFplusQGrid.addWidget(self.FreqStopQLCD, 3, 1, 1, 1)
        self.NewValQLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.NewValQLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.NewValQLabel_2.setObjectName("NewValQLabel_2")
        self.SFplusQGrid.addWidget(self.NewValQLabel_2, 0, 2, 1, 1)
        self.PulseTimeStopQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.PulseTimeStopQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.PulseTimeStopQLineEdit.setObjectName("PulseTimeStopQLineEdit")
        self.SFplusQGrid.addWidget(self.PulseTimeStopQLineEdit, 6, 2, 1, 1)
        self.OutputFreqQLCD = QtWidgets.QLCDNumber(self.gridLayoutWidget_4)
        self.OutputFreqQLCD.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputFreqQLCD.sizePolicy().hasHeightForWidth())
        self.OutputFreqQLCD.setSizePolicy(sizePolicy)
        self.OutputFreqQLCD.setMinimumSize(QtCore.QSize(122, 0))
        self.OutputFreqQLCD.setMaximumSize(QtCore.QSize(200, 50))
        self.OutputFreqQLCD.setDigitCount(10)
        self.OutputFreqQLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.OutputFreqQLCD.setObjectName("OutputFreqQLCD")
        self.SFplusQGrid.addWidget(self.OutputFreqQLCD, 1, 1, 1, 1)
        self.FreqStartQLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.FreqStartQLineEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.FreqStartQLineEdit.setObjectName("FreqStartQLineEdit")
        self.SFplusQGrid.addWidget(self.FreqStartQLineEdit, 2, 2, 1, 1)
        self.VariableQLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VariableQLabel_2.setMinimumSize(QtCore.QSize(153, 16))
        self.VariableQLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.VariableQLabel_2.setObjectName("VariableQLabel_2")
        self.SFplusQGrid.addWidget(self.VariableQLabel_2, 0, 0, 1, 1)
        self.FreqStopUnitComboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FreqStopUnitComboBox.sizePolicy().hasHeightForWidth())
        self.FreqStopUnitComboBox.setSizePolicy(sizePolicy)
        self.FreqStopUnitComboBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.FreqStopUnitComboBox.setObjectName("FreqStopUnitComboBox")
        self.FreqStopUnitComboBox.addItem("")
        self.FreqStopUnitComboBox.addItem("")
        self.FreqStopUnitComboBox.addItem("")
        self.SFplusQGrid.addWidget(self.FreqStopUnitComboBox, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SFplusQGrid.addItem(spacerItem4, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.SFplusQGrid.addWidget(self.label_2, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.SFplusQGrid.addWidget(self.label_3, 6, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.SFplusQGrid.addWidget(self.label_4, 0, 3, 1, 1)
        self.VariableTabWidget.addTab(self.SFplusTab, "")
        self.gridLayout.addWidget(self.VariableTabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.VariableTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.CommQTextBrowser.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>", None, -1))
        self.COM_Label.setText(QtWidgets.QApplication.translate("MainWindow", "COM PORT: ", None, -1))
        self.ConnectedRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connected", None, -1))
        self.ConnectButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.DisconnectButton.setText(QtWidgets.QApplication.translate("MainWindow", "Disconnect", None, -1))
        self.ModeSelect_Label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Mode Selection Drop Down</p></body></html>", None, -1))
        self.ModeSelect_Label.setText(QtWidgets.QApplication.translate("MainWindow", "Mode Select", None, -1))
        self.ModeSelectDropDown.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Single Frequency", None, -1))
        self.ModeSelectDropDown.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Spectroscopy", None, -1))
        self.ModeSelectDropDown.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Rabi Scan", None, -1))
        self.ModeSelectDropDown.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Frequency Sweep Scan", None, -1))
        self.UploadButton.setText(QtWidgets.QApplication.translate("MainWindow", "Upload", None, -1))
        self.NewValQLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "New Value", None, -1))
        self.RunsPerStepQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Runs Per Step", None, -1))
        self.CurrentValQLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "Current Value", None, -1))
        self.NumStepsQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Number of Steps", None, -1))
        self.VariableQLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "units", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "steps", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "steps", None, -1))
        self.VariableTabWidget.setTabText(self.VariableTabWidget.indexOf(self.GeneralTab), QtWidgets.QApplication.translate("MainWindow", "General", None, -1))
        self.SweepRateStopQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Rate Stop", None, -1))
        self.NewValQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "New Value", None, -1))
        self.SweepSpanQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Span", None, -1))
        self.SweepCenterFreqQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Center Frequency", None, -1))
        self.SweepRateQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Rate", None, -1))
        self.VariableQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.SweepLowerBoundQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Lower Bound", None, -1))
        self.SweepUpperBoundQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Upper Bound", None, -1))
        self.SweepRateStartQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Sweep Rate Start", None, -1))
        self.CurrentValQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Current Value", None, -1))
        self.SweepUpperBoundUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.SweepUpperBoundUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.SweepUpperBoundUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.SweepLowerBoundUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.SweepLowerBoundUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.SweepLowerBoundUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.SweepCenterFreqUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.SweepCenterFreqUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.SweepCenterFreqUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.SweepSpanUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.SweepSpanUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.SweepSpanUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "units", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "MHz/ms", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "MHz/ms", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "MHz/ms", None, -1))
        self.VariableTabWidget.setTabText(self.VariableTabWidget.indexOf(self.FreqSweepTab), QtWidgets.QApplication.translate("MainWindow", "Frequency Sweep", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "us", None, -1))
        self.OutputFreqUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.OutputFreqUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.OutputFreqUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.FreqStartUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.FreqStartUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.FreqStartUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.CurrentValQLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Current Value", None, -1))
        self.PulseTimeQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Pulse Time", None, -1))
        self.FreqStartQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Frequency Start", None, -1))
        self.PulseTimeStartQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Pulse Time Start", None, -1))
        self.FreqStopQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Frequency Stop", None, -1))
        self.OutputFreqQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Output Frequency", None, -1))
        self.PulseTimeStopQLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Pulse Time Stop", None, -1))
        self.NewValQLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "New Value", None, -1))
        self.VariableQLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Variable", None, -1))
        self.FreqStopUnitComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Hz", None, -1))
        self.FreqStopUnitComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "kHz", None, -1))
        self.FreqStopUnitComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "us", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "us", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "units", None, -1))
        self.VariableTabWidget.setTabText(self.VariableTabWidget.indexOf(self.SFplusTab), QtWidgets.QApplication.translate("MainWindow", "Single Frequency, Spectro, Rabi Flop", None, -1))

